package ext_animorphs;

public enum SoldierState {
	IDLE, BUILD_TOWER, BUILD_PASTR, ASSAULT, RALLY, DEFEND, CONSTRUCTING, BUILD_DISRUPTER,
	// DEPRECATED
	ATTACK_MOVE, SUICIDE, FIGHT, RETREAT, HOLD;
}
